POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Foo",
    "number": "123456789"
}

### Create duplicate:

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Foo",
    "number": "123456789"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Foo"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Fo",
    "number": "123"
}